/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: daCruz (https://sketchfab.com/daCruz)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/cyberpunk-bike-efcf679a115c487face1adc2ce7e8b8c
title: Cyberpunk bike
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Cyber({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/cyberBike.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[615.1, -51.26, 52.76]} rotation={[0, 0, -3.14]} scale={0.01}>
        <mesh castShadow receiveShadow geometry={nodes.Object_2.geometry} material={materials.lambert3SG} />
        <mesh castShadow receiveShadow geometry={nodes.Object_3.geometry} material={materials.initialShadingGroup} />
        <mesh castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials.initialShadingGroup} />
      </group>
    </group>
  )
}

useGLTF.preload('/cyberBike.glb')